
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
// 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const USER_IMAGE_SUCCESS = "USER_IMAGE_SUCCESS";
export const USER_IMAGE_BASE_URL_SUCCESS = "USER_IMAGE_BASE_URL_SUCCESS";
// 
export const USER_EMAIL_SUCCESS = "USER_EMAIL_SUCCESS";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const GET_USERS = "GET_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const LOADING_USERS = "LOADING_USERS"
export const GET_VERTCALS = "GET_VERTICALS"
export const CREATE_MERCHANT = "CREATE_MERCHANT"
export const CREATE_VERTICAL = "CREATE_VERTICAL"  
export const GET_VERTICALS = "GET_VERTICALS"  
export const LOADING_VERTICALS = "LOADING_VERTICALS" 
export const GET_MERCHANTS = "GET_MERCHANTS" 
export const ADD_CARTEGORY = "ADD_CARTEGORY"
export const ADD_HASHTAG = "ADD_HASHTAG"
export const ADD_HASHTAG_ENTRY = "ADD_HASHTAG_ENTRY"
export const CREATE_SPONSOR = "CREATE_SPONSOR"
export const DELETE_SPONSOR = "DELETE_SPONSOR"
export const GET_SPONSOR = "GET_SPONSOR"
export const GET_SPONSORS = "GET_SPONSORS"
export const EDIT_SPONSOR = "EDIT_SPONSOR"
export const GET_HASHTAGS = "GET_HASHTAGS"
export const CREATE_HASHTAG = "CREATE_HASHTAG"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const DELETE_HASHTAG = "DELETE_HASHTAG"
export const EDIT_HASHTAG = "EDIT_HASHTAG"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const CREATE_CHALLENGE = "CREATE_CHALLENGE"
export const EDIT_CHALLENGE = "EDIT_CHALLENGE"
export const GET_CHALLENGES = "GET_CHALLENGES"
export const DELETE_CHALLENGE = "DELETE_CHALLENGE"
export const CREATE_ENTRY = "CREATE_ENTRY"
export const EDIT_ENTRY = "EDIT_ENTRY"
export const GET_ENTRIES = "GET_ENTRIES"
export const DELETE_ENTRY = "DELETE_ENTRY"
export const CREATE_ENTRYCOMMENT = "CREATE_ENTRYCOMMENT"
export const GET_ENTRIESCOMMENT = "GET_ENTRIESCOMMENT"
export const DELETE_ENTRYCOMMENT = "DELETE_ENTRYCOMMENT"
export const EDIT_ENTRYCOMMENT = "EDIT_ENTRYCOMMENT"
export const CREATE_ENTRYDATA = "CREATE_ENTRYDATA"
export const GET_ENTRIESDATA = "GET_ENTRIESDATA"
export const DELETE_ENTRYDATA = "DELETE_ENTRYDATA"



          
          
          